name: Create a comment on new issues

on:
  issues:
    types: 
      - opened


jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: Dump github contexts
        run: echo ${{ toJSON(github.event)}} | jq
        shell: bash